%YAML 1.2
--- 
name: "BT3-768x15x24h" # Daniel wuz here
gpu: all
dataset:
  num_chunks: 300_000_000
  allow_less_chunks: true
  train_ratio: 0.95
  sort_type: name
  input_train: 
    - "/mnt/rescored-data/*/"
  input_test:
    - "/mnt/test-data/*/"
  input_validation:
    - "/mnt/validation-data/"
  experimental_v5_only_dataset: false
  train_workers: 95
  test_workers: 4
training:
    precision: single
    swa: true
    swa_output: true    
    swa_max_n: 10
    swa_steps: 100
    max_grad_norm: 10
    batch_size: 4096
    num_batch_splits: 1
    q_ratio: 0
    value_focus_min: 0.025
    value_focus_slope: 3.0
    lookahead_optimizer: false
    renorm: true
    renorm_max_r: 1.0
    renorm_max_d: 0.0
    test_steps: 2500
    validation_steps: 2500
    num_test_positions: 131_072
    train_avg_report_steps: 500
    total_steps: 200_000_000
    checkpoint_steps: 10_000
    shuffle_size: 500_000
    warmup_steps: 1000
    mask_legal_moves: true
    lr_values: # schedule is likely outdated
        - 0.0005
        - 0.0005
    lr_boundaries:
        - 100 
    loss_weights:
        policy: 1.0
        policy_optimistic_st: 4.0
        policy_soft: 4.0 # loss is much smaller at optimum
        value_winner: 1.0
        value_q: 1.0
        value_st: 5.0 # larger because mse loss
        value_q_err: 5.0  # both error weights should be the same
        value_st_err: 5.0
        moves_left: 1.0
        reg: 1.0

    path: "/mnt/networks"

    optimizer: nadam # sgd/nadam/rmsprop/adabelief
    beta_1: 0.9 
    beta_2: 0.999  # these values are only for Nadam
    epsilon: 0.0000001 # 1e-7
    sparse: false

model:              
    embedding_size: 768
    policy_embedding_size: 768
    value_embedding_size: 32
    moves_left_embedding_size: 8
    encoder_layers: 15                   # number of intermediate attention layers in the policy head
    encoder_heads: 24                     # number of attention heads in encoder layers, emb // (32 or 64) recommended
                                         # with 64 memory is same as embedding, with 32 is double
    encoder_d_model: 768                 # size of the Q, K, & V vectors in encoder layers -- divisible by encoder_heads
    encoder_dff: 1024                    # size of the expansion layer in encoder layer ffn
    ffn_activation: "mish"
    policy_d_model: 768                  # size of the query and key vectors in final attention layer
    dropout_rate: 0.0                    # the dropout rate used for weight regularization of attention during training
                                        # makes memory 33 -> 39 GB on A100 as observed by Teck and Kovax
    
    embedding_dense_sz: 128           # number of params added is 50k times this number so care is needed
    skip_first_ln: false               # makes training unstable
    embedding_style: "new"

    
    value: "wdl"
    moves_left: "v1"
    input_type: "classic"

    # degrades performance, not recommended
    arc_encoding: false
    
    # smolgen: more efficient version of fullgen, adds a lot of params
    use_smolgen: true
    smolgen_hidden_channels: 32
    smolgen_hidden_sz: 256
    smolgen_gen_sz: 256

    # Enable or disable BT3 features
    policy_optimistic_st: true
    value_st: true
    soft_policy: true

    soft_policy_temperature: 4.0
